apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  accessModes:       
    - ReadWriteOnce
  capacity:          
    storage: 10Gi
  nfs:            #NFS设置
    server: 172.20.48.54
    path: /nfs/sonarqube/sonar
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: kube-ops
  name: sonarqube-data
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  #设置大小为5G
  selector:
    matchLabels:
      app: sonarqube
