apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-ops
  name: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.21.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: web # web ui for management
          containerPort: 8081 # port of web management
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m # default reqirement
            memory: 512Mi
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-ops
  name: nexus
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30004
